GET http://localhost:3003/users?type=te

###

GET http://localhost:3003/users/order?order=name&orderType=desc

###

GET http://localhost:3003/users?page=3&type=te

###

GET http://localhost:3003/users/all?name=te