GET http://localhost:3003/ping

###

GET http://localhost:3003/actors/search?name=Moacyr+Franco

###

GET http://localhost:3003/actors/search?gender=male

###

PUT http://localhost:3003/actors/2/edit
Content-Type: application/json

{
  "salary": 10
}

###

DELETE http://localhost:3003/actors/02

###

GET http://localhost:3003/actors/salary?gender=male

###

GET http://localhost:3003/actors/3

###

POST http://localhost:3003/actors
Content-Type: application/json

{
"id": 3,
  "salary": 30000
}