GET http://localhost:3003/ping

###

PUT http://localhost:3003/user
Content-Type: application/json

{
"name" : "Samuel",
  "nickname" : "sam99",
  "email" : "sam@gmail.com"
}

###

GET http://localhost:3003/user/162246778234